changelog:
  categories:
    - title: Features
      labels: [feature, enhancement]
    - title: Security & Safety
      labels: [security, safety]
    - title: Fixes
      labels: [bug, fix]
    - title: Documentation
      labels: [documentation, docs]
    - title: Other Changes
      labels: ['*']
